### ISSUE TITLE
Patch compiles and works for the update of the same UI

### ISSUE THREAD

**Issue by yevhey** [grammarly/embrace#4]
Hello again 🙂 

I've encountered two more issues to discuss to understand the library fully!

1. It's said in README that you can create a simple component without any flow at all, but then it renders nothing:
https://codesandbox.io/s/simple-component-o4z4pg

2. One of the coolest features for me was that it wouldn't compile if somebody tried to patch the same piece of UI. But here, it does compile and works as usual:
https://codesandbox.io/s/patch-issue-vrzvh7

**Comment by yevhey** [comment]
@akryvomaz 
1. Here's the line of code: https://github.com/grammarly/embrace/blob/main/README.md?plain=1#L51
2. Then you probably should change [the presentation](https://youtu.be/RcBDglcJlx4?t=2435) as well:
<img width="1049" alt="Screenshot 2022-11-21 at 13 46 50" src="https://user-images.githubusercontent.com/13643681/203043870-f15b5180-5ac5-4826-89cf-579c68a67ffa.png">

**Comment by AlexSugak** [comment]
I think the confusion about `UI.patch` here is because we did not implement the type checking of the UI tree path, see [TODO in code](https://github.com/grammarly/embrace/blob/main/src/ui.ts#L669 )

But the UI tree is changed after the patch, which you can see in the type of the UIPart returned, see the [code sandbox](https://codesandbox.io/s/patch-issue-forked-54xfu2?file=/src/App.tsx)

So the presentation is a bit ahead of itself, promising on the feature that is not yet fully implemented, sorry for that.

**Comment by yevhey** [comment]
Sure, thank you very much for the explanation 👍
